volumes:
  keeper_training_production_postgres_data: {}
  keeper_training_production_postgres_data_backups: {}
  keeper_training_production_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: keeper_training_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: keeper_training_production_postgres
    volumes:
      - keeper_training_production_postgres_data:/var/lib/postgresql/18/docker
      - keeper_training_production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: keeper_training_production_traefik
    depends_on:
      - django
    volumes:
      - keeper_training_production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:7.2
