volumes:
  keeper_training_local_postgres_data: {}
  keeper_training_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: keeper_training_local_django
    container_name: keeper_training_local_django
    depends_on:
      - postgres
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: keeper_training_production_postgres
    container_name: keeper_training_local_postgres
    volumes:
      - keeper_training_local_postgres_data:/var/lib/postgresql/18/docker
      - keeper_training_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: keeper_training_local_docs
    container_name: keeper_training_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs
      - ./config:/app/config
      - ./keeper_training:/app/keeper_training
    ports:
      - '7000:7000'
